/**
 * @license
 * Lo-Dash 2.2.1 (Custom Build) lodash.com/license | Underscore.js 1.5.2 underscorejs.org/LICENSE
 * Build: `lodash modern exports="none" iife="(function(window){%output%;lodash.extend(Physics.util, lodash);}(this));" include="isObject,isFunction,isArray,isPlainObject,uniqueId,uniq,filter,find,each,random,extend,transform,clone,throttle,bind,sortedIndex,shuffle" --minify --output lib/lodash.js`
 */
;(function(H){function N(a,b,c){c=(c||0)-1;for(var d=a?a.length:0;++c<d;)if(a[c]===b)return c;return-1}function Da(a,b){var c=typeof b;a=a.l;if("boolean"==c||null==b)return a[b]?0:-1;"number"!=c&&"string"!=c&&(c="object");var d="number"==c?b:na+b;a=(a=a[c])&&a[d];return"object"==c?a&&-1<N(a,b)?0:-1:a?0:-1}function Ea(a){var b=this.l,c=typeof a;if("boolean"==c||null==a)b[a]=!0;else{"number"!=c&&"string"!=c&&(c="object");var d="number"==c?a:na+a,b=b[c]||(b[c]={});"object"==c?(b[d]||(b[d]=[])).push(a):
b[d]=!0}}function I(){return ba.pop()||[]}function oa(){return ca.pop()||{k:null,l:null,"false":!1,"null":!1,number:null,object:null,push:null,string:null,"true":!1,undefined:!1}}function O(){}function z(a){a.length=0;ba.length<pa&&ba.push(a)}function qa(a){var b=a.l;b&&qa(b);a.k=a.l=a.object=a.number=a.string=null;ca.length<pa&&ca.push(a)}function Fa(a,b,c){b||(b=0);typeof c=="undefined"&&(c=a?a.length:0);var d=-1;c=c-b||0;for(var e=Array(0>c?0:c);++d<c;)e[d]=a[b+d];return e}function f(){}function ra(a,
b,c,d,e){if(c){var g=c(a);if(typeof g!="undefined")return g}if(t(a)){var k=A.call(a);if(!q[k])return a;var l=u[k];switch(k){case P:case Q:return new l(+a);case R:case S:return new l(a);case T:return g=l(a.source,Ga.exec(a)),g.lastIndex=a.lastIndex,g}}else return a;k=da(a);if(b){var h=!d;d||(d=I());e||(e=I());for(var p=d.length;p--;)if(d[p]==a)return e[p];g=k?l(a.length):{}}else g=k?Fa(a):ea({},a);k&&(v.call(a,"index")&&(g.index=a.index),v.call(a,"input")&&(g.input=a.input));if(!b)return g;d.push(a);
e.push(g);(k?J:F)(a,function(a,k){g[k]=ra(a,b,c,d,e)});h&&(z(d),z(e));return g}function B(a,b,c){if(typeof a!="function")return fa;if(typeof b=="undefined")return a;var d=a.__bindData__||x.funcNames&&!a.name;if(typeof d=="undefined"){var e=ga&&Ha.call(a);x.funcNames||!e||Ia.test(e)||(d=!0);if(x.funcNames||!d)d=!x.funcDecomp||ga.test(e),sa(a,d)}if(true!==d&&d&&d[1]&1)return a;switch(c){case 1:return function(c){return a.call(b,c)};case 2:return function(c,d){return a.call(b,c,d)};case 3:return function(c,
d,e){return a.call(b,c,d,e)};case 4:return function(c,d,e,h){return a.call(b,c,d,e,h)}}return ta(a,b)}function K(a,b,c,d,e,g){if(c){var k=c(a,b);if(typeof k!="undefined")return!!k}if(a===b)return 0!==a||1/a==1/b;if(a===a&&!(a&&n[typeof a]||b&&n[typeof b]))return!1;if(null==a||null==b)return a===b;var l=A.call(a),h=A.call(b);l==ha&&(l=C);h==ha&&(h=C);if(l!=h)return!1;switch(l){case P:case Q:return+a==+b;case R:return a!=+a?b!=+b:0==a?1/a==1/b:a==+b;case T:case S:return a==String(b)}h=l==U;if(!h){if(v.call(a,
"__wrapped__")||v.call(b,"__wrapped__"))return K(a.__wrapped__||a,b.__wrapped__||b,c,d,e,g);if(l!=C)return!1;var l=a.constructor,p=b.constructor;if(l!=p&&!(D(l)&&l instanceof l&&D(p)&&p instanceof p))return!1}p=!e;e||(e=I());g||(g=I());for(l=e.length;l--;)if(e[l]==a)return g[l]==b;var f=0,k=!0;e.push(a);g.push(b);if(h){l=a.length;f=b.length;k=f==a.length;if(!k&&!d)return k;for(;f--;)if(h=l,p=b[f],d)for(;h--&&!(k=K(a[h],p,c,d,e,g)););else if(!(k=K(a[f],p,c,d,e,g)))break;return k}V(b,function(b,h,l){if(v.call(l,
h))return f++,k=v.call(a,h)&&K(a[h],b,c,d,e,g)});k&&!d&&V(a,function(a,b,c){if(v.call(c,b))return k=-1<--f});p&&(z(e),z(g));return k}function W(a,b,c,d,e,g){var k=b&1,l=b&2,h=b&4,f=b&8,s=b&16,r=b&32,Ja=a;if(!l&&!D(a))throw new TypeError;s&&!c.length&&(b&=-17,s=c=!1);r&&!d.length&&(b&=-33,r=d=!1);var m=a&&a.__bindData__;if(m)return!k||m[1]&1||(m[4]=e),!k&&m[1]&1&&(b|=8),!h||m[1]&4||(m[5]=g),s&&X.apply(m[2]||(m[2]=[]),c),r&&X.apply(m[3]||(m[3]=[]),d),m[1]|=b,W.apply(null,m);if(!k||l||h||r||!(x.fastBind||
y&&s))q=function(){var m=arguments,n=k?e:this;if(h||s||r)if(m=ia.call(m),s&&Ka.apply(m,c),r&&X.apply(m,d),h&&m.length<g)return b|=16,W(a,f?b:b&-4,m,null,e,g);l&&(a=n[Ja]);return this instanceof q?(n=ja(a.prototype),m=a.apply(n,m),t(m)?m:n):a.apply(n,m)};else{if(s){var n=[e];X.apply(n,c)}var q=s?y.apply(a,n):y.call(a,e)}sa(q,ia.call(arguments));return q}function ja(a){return t(a)?Y(a):{}}function La(a){var b,c;if(!a||A.call(a)!=C||(b=a.constructor,D(b)&&!(b instanceof b)))return!1;V(a,function(a,b){c=
b});return typeof c=="undefined"||v.call(a,c)}function D(a){return typeof a=="function"}function t(a){return!(!a||!n[typeof a])}function ua(a,b,c){var d=[];b=f.createCallback(b,c,3);c=-1;var e=a?a.length:0;if(typeof e=="number")for(;++c<e;){var g=a[c];b(g,c,a)&&d.push(g)}else F(a,function(a,c,e){b(a,c,e)&&d.push(a)});return d}function ka(a,b,c){b=f.createCallback(b,c,3);c=-1;var d=a?a.length:0;if(typeof d=="number")for(;++c<d;){var e=a[c];if(b(e,c,a))return e}else{var g;F(a,function(a,c,d){if(b(a,c,
d))return g=a,!1});return g}}function J(a,b,c){var d=-1,e=a?a.length:0;b=b&&typeof c=="undefined"?b:B(b,c,3);if(typeof e=="number")for(;++d<e&&false!==b(a[d],d,a););else F(a,b);return a}function va(a,b,c){if(typeof c=="number"){var d=a?a.length:0;c=0>c?la(0,d+c):c||0}else if(c)return c=wa(a,b),a[c]===b?c:-1;return N(a,b,c)}function wa(a,b,c,d){var e=0,g=a?a.length:e;c=c?f.createCallback(c,d,1):fa;for(b=c(b);e<g;)d=e+g>>>1,c(a[d])<b?e=d+1:g=d;return e}function xa(a,b,c,d){typeof b!="boolean"&&null!=b&&
(c=(d=c)&&d[b]===a?null:b,b=!1);null!=c&&(c=f.createCallback(c,d,3));d=-1;var e;e=(e=f.indexOf)===va?N:e;var g=a?a.length:0,k=[],l=!b&&g>=Ma&&e===N,h=c||l?I():k;if(l){var p;p=h;var s=-1,r=p.length,n=p[0],m=p[r/2|0],q=p[r-1];if(n&&typeof n=="object"&&m&&typeof m=="object"&&q&&typeof q=="object")p=!1;else{n=oa();n["false"]=n["null"]=n["true"]=n.undefined=!1;m=oa();m.k=p;m.l=n;for(m.push=Ea;++s<r;)m.push(p[s]);p=m}p?(e=Da,h=p):(l=!1,h=c?h:(z(h),k))}for(;++d<g;)if(p=a[d],s=c?c(p,d,a):p,b?!d||h[h.length-
1]!==s:0>e(h,s))(c||l)&&h.push(s),k.push(p);l?(z(h.k),qa(h)):c&&z(h);return k}function ta(a,b){return 2<arguments.length?W(a,17,ia.call(arguments,2),null,b):W(a,1,null,null,b)}function ya(a,b,c){var d,e,g,k,l,h,f,n=0,r=!1,q=!0;if(!D(a))throw new TypeError;b=la(0,b)||0;if(true===c)var m=!0,q=!1;else t(c)&&(m=c.leading,r="maxWait"in c&&(la(b,c.maxWait)||0),q="trailing"in c?c.trailing:q);var u=function(){var c=b-(G()-k);0>=c?(e&&clearTimeout(e),c=f,e=h=f=za,c&&(n=G(),g=a.apply(l,d))):h=setTimeout(u,c)},
v=function(){h&&clearTimeout(h);e=h=f=za;if(q||r!==b)n=G(),g=a.apply(l,d)};return function(){d=arguments;k=G();l=this;f=q&&(h||!m);if(false===r)var c=m&&!h;else{e||m||(n=k);var t=r-(k-n);0>=t?(e&&(e=clearTimeout(e)),n=k,g=a.apply(l,d)):e||(e=setTimeout(v,t))}h||b===r||(h=setTimeout(u,b));c&&(g=a.apply(l,d));return g}}function fa(a){return a}function Aa(a,b,c){var d=null==a,e=null==b;null==c&&(typeof a=="boolean"&&e?(c=a,a=1):e||typeof b!="boolean"||(c=b,e=!0));d&&e&&(b=1);a=+a||0;e?(b=a,a=0):b=+b||0;
d=Na();return c||a%1||b%1?Oa(a+d*(b-a+parseFloat("1e-"+((d+"").length-1))),b):a+Pa(d*(b-a+1))}var za,ba=[],ca=[],Qa=0,na=+new Date+"",Ma=75,pa=40,Ga=/\w*$/,Ia=/^function[ \n\r\t]+\w/,ga=/\bthis\b/,ha="[object Arguments]",U="[object Array]",P="[object Boolean]",Q="[object Date]",R="[object Number]",C="[object Object]",T="[object RegExp]",S="[object String]",q={"[object Function]":!1};q[ha]=q[U]=q[P]=q[Q]=q[R]=q[C]=q[T]=q[S]=!0;var Z={leading:!1,maxWait:0,trailing:!1},Ba={configurable:!1,enumerable:!1,
value:null,writable:!1},n={"boolean":!1,"function":!0,object:!0,number:!1,string:!1,undefined:!1};H=n[typeof H]&&H||this;var E=[],ma=Object.prototype,w=RegExp("^"+String(ma.valueOf).replace(/[.*+?^${}()|[\]\\]/g,"\\$&").replace(/valueOf|for [^\]]+/g,".+?")+"$"),Pa=Math.floor,Ha=Function.prototype.toString,L=w.test(L=Object.getPrototypeOf)&&L,v=ma.hasOwnProperty,G=w.test(G=Date.now)&&G||function(){return+new Date},X=E.push,A=ma.toString,Ka=E.unshift,Ca=function(){try{var a={},b=w.test(b=Object.defineProperty)&&
b,c=b(a,a,a)&&b}catch(d){}return c}(),y=w.test(y=A.bind)&&y,Y=w.test(Y=Object.create)&&Y,M=w.test(M=Array.isArray)&&M,$=w.test($=Object.keys)&&$,la=Math.max,Oa=Math.min,Na=Math.random,ia=E.slice,E=w.test(H.attachEvent),E=y&&!/\n|true/.test(y+E),u={};u[U]=Array;u[P]=Boolean;u[Q]=Date;u["[object Function]"]=Function;u[C]=Object;u[R]=Number;u[T]=RegExp;u[S]=String;var x=f.support={};x.fastBind=y&&!E;x.funcDecomp=!w.test(H.WinRTError)&&ga.test(function(){return this});x.funcNames=typeof Function.name=="string";
Y||(ja=function(a){if(t(a)){O.prototype=a;var b=new O;O.prototype=null}return b||{}});var sa=Ca?function(a,b){Ba.value=b;Ca(a,"__bindData__",Ba)}:O,da=M||function(a){return a&&typeof a=="object"&&typeof a.length=="number"&&A.call(a)==U||!1},M=function(a){var b,c=[];if(!a||!n[typeof a])return c;for(b in a)v.call(a,b)&&c.push(b);return c},aa=$?function(a){return t(a)?$(a):[]}:M,ea=function(a,b,c){var d,e=a,g=e;if(!e)return g;var k=arguments,f=0,h=typeof c=="number"?2:k.length;if(3<h&&"function"==typeof k[h-
2])var p=B(k[--h-1],k[h--],2);else 2<h&&"function"==typeof k[h-1]&&(p=k[--h]);for(;++f<h;)if((e=k[f])&&n[typeof e])for(var q=-1,r=n[typeof e]&&aa(e),t=r?r.length:0;++q<t;)d=r[q],g[d]=p?p(g[d],e[d]):e[d];return g},V=function(a,b,c){var d;if(!a||!n[typeof a])return a;b=b&&typeof c=="undefined"?b:B(b,c,3);for(d in a)if(false===b(a[d],d,a))break;return a},F=function(a,b,c){if(!a||!n[typeof a])return a;b=b&&typeof c=="undefined"?b:B(b,c,3);for(var d=-1,e=n[typeof a]&&aa(a),g=e?e.length:0;++d<g&&(c=e[d],false!==
b(a[c],c,a)););return a};f.assign=ea;f.bind=ta;f.createCallback=function(a,b,c){var d=typeof a;if(null==a||"function"==d)return B(a,b,c);if("object"!=d)return function(b){return b[a]};var e=aa(a),g=e[0],f=a[g];return 1!=e.length||f!==f||t(f)?function(b){for(var c=e.length,d=!1;c--&&(d=K(b[e[c]],a[e[c]],null,!0)););return d}:function(a){a=a[g];return f===a&&(0!==f||1/f==1/a)}};f.debounce=ya;f.filter=ua;f.forEach=J;f.forIn=V;f.forOwn=F;f.keys=aa;f.shuffle=function(a){var b=-1,c=a?a.length:0,d=Array(typeof c=="number"?c:0);J(a,function(a){var c=Aa(++b);d[b]=d[c];d[c]=a});return d};f.throttle=function(a,b,c){var d=!0,e=!0;if(!D(a))throw new TypeError;false===c?d=!1:t(c)&&(d="leading"in c?c.leading:d,e="trailing"in c?c.trailing:e);Z.leading=d;Z.maxWait=b;Z.trailing=e;return ya(a,b,Z)};f.transform=function(a,b,c,d){var e=da(a);b=B(b,d,4);null==c&&(e?c=[]:(d=a&&a.constructor,c=ja(d&&d.prototype)));(e?J:F)(a,function(a,d,e){return b(c,a,d,e)});return c};f.uniq=xa;f.each=J;f.extend=ea;f.select=ua;f.unique=xa;f.clone=
function(a,b,c,d){typeof b!="boolean"&&null!=b&&(d=c,c=b,b=!1);return ra(a,b,typeof c=="function"&&B(c,d,1))};f.find=ka;f.identity=fa;f.indexOf=va;f.isArray=da;f.isFunction=D;f.isObject=t;f.isPlainObject=function(a){if(!a||A.call(a)!=C)return!1;var b=a.valueOf,c=typeof b=="function"&&(c=L(b))&&L(c);return c?a==c||L(a)==c:La(a)};f.random=Aa;f.sortedIndex=wa;f.uniqueId=function(a){var b=++Qa;return String(null==a?"":a)+b};f.detect=ka;f.findWhere=ka;f.VERSION="2.2.1";f.extend(Physics.util,f)})(this);