/**
 * @license
 * Lo-Dash 2.4.1 (Custom Build) lodash.com/license | Underscore.js 1.5.2 underscorejs.org/LICENSE
 * Build: `lodash exports="none" iife="(function(window){%output%;lodash.extend(Physics.util, lodash);}(this));" include="isObject,isFunction,isArray,isPlainObject,uniqueId,each,random,extend,clone,throttle,bind,sortedIndex,shuffle" --minify --output lib/lodash.js`
 */
;!function(n){function t(n){return typeof n.toString!="function"&&typeof(n+"")=="string"}function e(n){n.length=0,S.length<P&&S.push(n)}function r(n,t,e){t||(t=0),typeof e=="undefined"&&(e=n?n.length:0);var r=-1;e=e-t||0;for(var o=Array(0>e?0:e);++r<e;)o[r]=n[t+r];return o}function o(){}function u(n){function t(){if(o){var n=r(o);at.apply(n,arguments)}if(this instanceof t){var a=i(e.prototype),n=e.apply(a,n||arguments);return b(n)?n:a}return e.apply(u,n||arguments)}var e=n[0],o=n[2],u=n[4];return dt(t,n),t
}function a(n,o,u,i,c){if(u){var l=u(n);if(typeof l!="undefined")return l}if(!b(n))return n;var f=nt.call(n);if(!q[f]||!mt.nodeClass&&t(n))return n;var s=ht[f];switch(f){case N:case R:return new s(+n);case M:case K:return new s(n);case z:return l=s(n.source,D.exec(n)),l.lastIndex=n.lastIndex,l}if(f=jt(n),o){var p=!i;i||(i=S.pop()||[]),c||(c=S.pop()||[]);for(var g=i.length;g--;)if(i[g]==n)return c[g];l=f?s(n.length):{}}else l=f?r(n):_t({},n);return f&&(ut.call(n,"index")&&(l.index=n.index),ut.call(n,"input")&&(l.input=n.input)),o?(i.push(n),c.push(l),(f?Ot:At)(n,function(n,t){l[t]=a(n,o,u,i,c)
}),p&&(e(i),e(c)),l):l}function i(n){return b(n)?ft(n):{}}function c(n,t,e){if(typeof n!="function")return E;if(typeof t=="undefined"||!("prototype"in n))return n;var r=n.__bindData__;if(typeof r=="undefined"&&(mt.funcNames&&(r=!n.name),r=r||!mt.funcDecomp,!r)){var o=rt.call(n);mt.funcNames||(r=!T.test(o)),r||(r=F.test(o),dt(n,r))}if(false===r||true!==r&&1&r[1])return n;switch(e){case 1:return function(e){return n.call(t,e)};case 2:return function(e,r){return n.call(t,e,r)};case 3:return function(e,r,o){return n.call(t,e,r,o)
};case 4:return function(e,r,o,u){return n.call(t,e,r,o,u)}}return j(n,t)}function l(n){function t(){var n=s?c:this;if(u){var h=r(u);at.apply(h,arguments)}return(a||g)&&(h||(h=r(arguments)),a&&at.apply(h,a),g&&h.length<f)?(o|=16,l([e,y?o:-4&o,h,null,c,f])):(h||(h=arguments),p&&(e=n[v]),this instanceof t?(n=i(e.prototype),h=e.apply(n,h),b(h)?h:n):e.apply(n,h))}var e=n[0],o=n[1],u=n[2],a=n[3],c=n[4],f=n[5],s=1&o,p=2&o,g=4&o,y=8&o,v=e;return dt(t,n),t}function f(n,r,o,u,a,i){if(o){var c=o(n,r);if(typeof c!="undefined")return!!c
}if(n===r)return 0!==n||1/n==1/r;if(n===n&&!(n&&V[typeof n]||r&&V[typeof r]))return false;if(null==n||null==r)return n===r;var l=nt.call(n),s=nt.call(r);if(l==B&&(l=$),s==B&&(s=$),l!=s)return false;switch(l){case N:case R:return+n==+r;case M:return n!=+n?r!=+r:0==n?1/n==1/r:n==+r;case z:case K:return n==r+""}if(s=l==L,!s){var p=ut.call(n,"__wrapped__"),g=ut.call(r,"__wrapped__");if(p||g)return f(p?n.__wrapped__:n,g?r.__wrapped__:r,o,u,a,i);if(l!=$||!mt.nodeClass&&(t(n)||t(r)))return false;if(l=!mt.argsObject&&v(n)?Object:n.constructor,p=!mt.argsObject&&v(r)?Object:r.constructor,l!=p&&!(h(l)&&l instanceof l&&h(p)&&p instanceof p)&&"constructor"in n&&"constructor"in r)return false
}for(l=!a,a||(a=S.pop()||[]),i||(i=S.pop()||[]),p=a.length;p--;)if(a[p]==n)return i[p]==r;var y=0,c=true;if(a.push(n),i.push(r),s){if(p=n.length,y=r.length,(c=y==p)||u)for(;y--;)if(s=p,g=r[y],u)for(;s--&&!(c=f(n[s],g,o,u,a,i)););else if(!(c=f(n[y],g,o,u,a,i)))break}else St(r,function(t,e,r){return ut.call(r,e)?(y++,c=ut.call(n,e)&&f(n[e],t,o,u,a,i)):void 0}),c&&!u&&St(n,function(n,t,e){return ut.call(e,t)?c=-1<--y:void 0});return a.pop(),i.pop(),l&&(e(a),e(i)),c}function s(n,t,e,o,a,i){var c=1&t,f=4&t,p=16&t,g=32&t;
if(!(2&t||h(n)))throw new TypeError;p&&!e.length&&(t&=-17,p=e=false),g&&!o.length&&(t&=-33,g=o=false);var y=n&&n.__bindData__;return y&&true!==y?(y=r(y),y[2]&&(y[2]=r(y[2])),y[3]&&(y[3]=r(y[3])),!c||1&y[1]||(y[4]=a),!c&&1&y[1]&&(t|=8),!f||4&y[1]||(y[5]=i),p&&at.apply(y[2]||(y[2]=[]),e),g&&ct.apply(y[3]||(y[3]=[]),o),y[1]|=t,s.apply(null,y)):(1==t||17===t?u:l)([n,t,e,o,a,i])}function p(){H.h=I,H.b=H.c=H.g=H.i="",H.e="t",H.j=true;for(var n,t=0;n=arguments[t];t++)for(var e in n)H[e]=n[e];t=H.a,H.d=/^[^,]+/.exec(t)[0],n=Function,t="return function("+t+"){",e=H;
var r="var n,t="+e.d+",E="+e.e+";if(!t)return E;"+e.i+";";e.b?(r+="var u=t.length;n=-1;if("+e.b+"){",mt.unindexedChars&&(r+="if(s(t)){t=t.split('')}"),r+="while(++n<u){"+e.g+";}}else{"):mt.nonEnumArgs&&(r+="var u=t.length;n=-1;if(u&&p(t)){while(++n<u){n+='';"+e.g+";}}else{"),mt.enumPrototypes&&(r+="var G=typeof t=='function';"),mt.enumErrorProps&&(r+="var F=t===k||t instanceof Error;");var o=[];if(mt.enumPrototypes&&o.push('!(G&&n=="prototype")'),mt.enumErrorProps&&o.push('!(F&&(n=="message"||n=="name"))'),e.j&&e.f)r+="var C=-1,D=B[typeof t]&&v(t),u=D?D.length:0;while(++C<u){n=D[C];",o.length&&(r+="if("+o.join("&&")+"){"),r+=e.g+";",o.length&&(r+="}"),r+="}";
else if(r+="for(n in t){",e.j&&o.push("m.call(t, n)"),o.length&&(r+="if("+o.join("&&")+"){"),r+=e.g+";",o.length&&(r+="}"),r+="}",mt.nonEnumShadows){for(r+="if(t!==A){var i=t.constructor,r=t===(i&&i.prototype),f=t===J?I:t===k?j:L.call(t),x=y[f];",k=0;7>k;k++)r+="n='"+e.h[k]+"';if((!(r&&x[n])&&m.call(t,n))",e.j||(r+="||(!x[n]&&t[n]!==A[n])"),r+="){"+e.g+"}";r+="}"}return(e.b||mt.nonEnumArgs)&&(r+="}"),r+=e.c+";return E",n("d,j,k,m,o,p,q,s,v,A,B,y,I,J,L",t+r+"}")(c,W,X,ut,C,v,jt,m,H.f,Y,V,bt,K,Z,nt)
}function g(n){return typeof n=="function"&&tt.test(n)}function y(n){var e,r;return!n||nt.call(n)!=$||(e=n.constructor,h(e)&&!(e instanceof e))||!mt.argsClass&&v(n)||!mt.nodeClass&&t(n)?false:mt.ownLast?(St(n,function(n,t,e){return r=ut.call(e,t),false}),false!==r):(St(n,function(n,t){r=t}),typeof r=="undefined"||ut.call(n,r))}function v(n){return n&&typeof n=="object"&&typeof n.length=="number"&&nt.call(n)==B||false}function h(n){return typeof n=="function"}function b(n){return!(!n||!V[typeof n])}function m(n){return typeof n=="string"||n&&typeof n=="object"&&nt.call(n)==K||false
}function d(n,t,e){if(t&&typeof e=="undefined"&&jt(n)){e=-1;for(var r=n.length;++e<r&&false!==t(n[e],e,n););}else Ot(n,t,e);return n}function j(n,t){return 2<arguments.length?s(n,17,r(arguments,2),null,t):s(n,1,null,null,t)}function w(n,t,e){var r,o,u,a,i,c,l,f=0,s=false,p=true;if(!h(n))throw new TypeError;if(t=gt(0,t)||0,true===e)var g=true,p=false;else b(e)&&(g=e.leading,s="maxWait"in e&&(gt(t,e.maxWait)||0),p="trailing"in e?e.trailing:p);var y=function(){var e=t-(Ct()-a);0<e?c=setTimeout(y,e):(o&&clearTimeout(o),e=l,o=c=l=_,e&&(f=Ct(),u=n.apply(i,r),c||o||(r=i=null)))
},v=function(){c&&clearTimeout(c),o=c=l=_,(p||s!==t)&&(f=Ct(),u=n.apply(i,r),c||o||(r=i=null))};return function(){if(r=arguments,a=Ct(),i=this,l=p&&(c||!g),false===s)var e=g&&!c;else{o||g||(f=a);var h=s-(a-f),b=0>=h;b?(o&&(o=clearTimeout(o)),f=a,u=n.apply(i,r)):o||(o=setTimeout(v,h))}return b&&c?c=clearTimeout(c):c||t===s||(c=setTimeout(y,t)),e&&(b=true,u=n.apply(i,r)),!b||c||o||(r=i=null),u}}function E(n){return n}function x(){}function O(n){return function(t){return t[n]}}var _,S=[],A=0,C={},P=40,D=/\w*$/,T=/^\s*function[ \n\r\t]+\w/,F=/\bthis\b/,I="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),B="[object Arguments]",L="[object Array]",N="[object Boolean]",R="[object Date]",W="[object Error]",M="[object Number]",$="[object Object]",z="[object RegExp]",K="[object String]",q={"[object Function]":false};
q[B]=q[L]=q[N]=q[R]=q[M]=q[$]=q[z]=q[K]=true;var G={leading:false,maxWait:0,trailing:false},J={configurable:false,enumerable:false,value:null,writable:false},H={a:"",b:null,c:"",d:"",e:"",v:null,g:"",h:null,support:null,i:"",j:false},V={"boolean":false,"function":true,object:true,number:false,string:false,undefined:false},Q=V[typeof n]&&n||this;n=V[typeof global]&&global,!n||n.global!==n&&n.window!==n||(Q=n);var U=[],X=Error.prototype,Y=Object.prototype,Z=String.prototype,nt=Y.toString,tt=RegExp("^"+(nt+"").replace(/[.*+?^${}()|[\]\\]/g,"\\$&").replace(/toString| for [^\]]+/g,".*?")+"$"),et=Math.floor,rt=Function.prototype.toString,ot=g(ot=Object.getPrototypeOf)&&ot,ut=Y.hasOwnProperty,at=U.push,it=Y.propertyIsEnumerable,ct=U.unshift,lt=function(){try{var n={},t=g(t=Object.defineProperty)&&t,e=t(n,n,n)&&t
}catch(r){}return e}(),ft=g(ft=Object.create)&&ft,st=g(st=Array.isArray)&&st,pt=g(pt=Object.keys)&&pt,gt=Math.max,yt=Math.min,vt=Math.random,ht={};ht[L]=Array,ht[N]=Boolean,ht[R]=Date,ht["[object Function]"]=Function,ht[$]=Object,ht[M]=Number,ht[z]=RegExp,ht[K]=String;var bt={};bt[L]=bt[R]=bt[M]={constructor:true,toLocaleString:true,toString:true,valueOf:true},bt[N]=bt[K]={constructor:true,toString:true,valueOf:true},bt[W]=bt["[object Function]"]=bt[z]={constructor:true,toString:true},bt[$]={constructor:true},function(){for(var n=I.length;n--;){var t,e=I[n];
for(t in bt)ut.call(bt,t)&&!ut.call(bt[t],e)&&(bt[t][e]=false)}}();var mt=o.support={};!function(){var n=function(){this.x=1},t={0:1,length:1},e=[];n.prototype={valueOf:1,y:1};for(var r in new n)e.push(r);for(r in arguments);mt.argsClass=nt.call(arguments)==B,mt.argsObject=arguments.constructor==Object&&!(arguments instanceof Array),mt.enumErrorProps=it.call(X,"message")||it.call(X,"name"),mt.enumPrototypes=it.call(n,"prototype"),mt.funcDecomp=!g(Q.WinRTError)&&F.test(function(){return this}),mt.funcNames=typeof Function.name=="string",mt.nonEnumArgs=0!=r,mt.nonEnumShadows=!/valueOf/.test(e),mt.ownLast="x"!=e[0],mt.spliceObjects=(U.splice.call(t,0,1),!t[0]),mt.unindexedChars="xx"!="x"[0]+Object("x")[0];
try{mt.nodeClass=!(nt.call(document)==$&&!({toString:0}+""))}catch(o){mt.nodeClass=true}}(1),ft||(i=function(){function n(){}return function(t){if(b(t)){n.prototype=t;var e=new n;n.prototype=null}return e||Q.Object()}}());var dt=lt?function(n,t){J.value=t,lt(n,"__bindData__",J)}:x;mt.argsClass||(v=function(n){return n&&typeof n=="object"&&typeof n.length=="number"&&ut.call(n,"callee")&&!it.call(n,"callee")||false});var jt=st||function(n){return n&&typeof n=="object"&&typeof n.length=="number"&&nt.call(n)==L||false
},wt=p({a:"z",e:"[]",i:"if(!(B[typeof z]))return E",g:"E.push(n)"}),Et=pt?function(n){return b(n)?mt.enumPrototypes&&typeof n=="function"||mt.nonEnumArgs&&n.length&&v(n)?wt(n):pt(n):[]}:wt,st={a:"g,e,K",i:"e=e&&typeof K=='undefined'?e:d(e,K,3)",b:"typeof u=='number'",v:Et,g:"if(e(t[n],n,g)===false)return E"};n={a:"z,H,l",i:"var a=arguments,b=0,c=typeof l=='number'?2:a.length;while(++b<c){t=a[b];if(t&&B[typeof t]){",v:Et,g:"if(typeof E[n]=='undefined')E[n]=t[n]",c:"}}"};var xt={i:"if(!B[typeof t])return E;"+st.i,b:false},Ot=p(st),_t=p(n,{i:n.i.replace(";",";if(c>3&&typeof a[c-2]=='function'){var e=d(a[--c-1],a[c--],2)}else if(c>2&&typeof a[c-1]=='function'){e=a[--c]}"),g:"E[n]=e?e(E[n],t[n]):t[n]"}),St=p(st,xt,{j:false}),At=p(st,xt);
h(/x/)&&(h=function(n){return typeof n=="function"&&"[object Function]"==nt.call(n)});var st=ot?function(n){if(!n||nt.call(n)!=$||!mt.argsClass&&v(n))return false;var t=n.valueOf,e=g(t)&&(e=ot(t))&&ot(e);return e?n==e||ot(n)==e:y(n)}:y,Ct=g(Ct=Date.now)&&Ct||function(){return(new Date).getTime()};o.assign=_t,o.bind=j,o.createCallback=function(n,t,e){var r=typeof n;if(null==n||"function"==r)return c(n,t,e);if("object"!=r)return O(n);var o=Et(n),u=o[0],a=n[u];return 1!=o.length||a!==a||b(a)?function(t){for(var e=o.length,r=false;e--&&(r=f(t[o[e]],n[o[e]],null,true)););return r
}:function(n){return n=n[u],a===n&&(0!==a||1/a==1/n)}},o.debounce=w,o.forEach=d,o.forIn=St,o.forOwn=At,o.keys=Et,o.property=O,o.shuffle=function(n){var t=-1,e=n?n.length:0,r=Array(typeof e=="number"?e:0);return d(n,function(n){var e;e=++t,e=0+et(vt()*(e-0+1)),r[t]=r[e],r[e]=n}),r},o.throttle=function(n,t,e){var r=true,o=true;if(!h(n))throw new TypeError;return false===e?r=false:b(e)&&(r="leading"in e?e.leading:r,o="trailing"in e?e.trailing:o),G.leading=r,G.maxWait=t,G.trailing=o,w(n,t,G)},o.each=d,o.extend=_t,o.clone=function(n,t,e,r){return typeof t!="boolean"&&null!=t&&(r=e,e=t,t=false),a(n,t,typeof e=="function"&&c(e,r,1))
},o.identity=E,o.isArguments=v,o.isArray=jt,o.isFunction=h,o.isObject=b,o.isPlainObject=st,o.isString=m,o.noop=x,o.now=Ct,o.random=function(n,t,e){var r=null==n,o=null==t;return null==e&&(typeof n=="boolean"&&o?(e=n,n=1):o||typeof t!="boolean"||(e=t,o=true)),r&&o&&(t=1),n=+n||0,o?(t=n,n=0):t=+t||0,e||n%1||t%1?(e=vt(),yt(n+e*(t-n+parseFloat("1e-"+((e+"").length-1))),t)):n+et(vt()*(t-n+1))},o.sortedIndex=function(n,t,e,r){var u=0,a=n?n.length:u;for(e=e?o.createCallback(e,r,1):E,t=e(t);u<a;)r=u+a>>>1,e(n[r])<t?u=r+1:a=r;
return u},o.uniqueId=function(n){var t=++A;return(null==n?"":n)+""+t},o.VERSION="2.4.1",o.extend(Physics.util,o)}(this);